### ISSUE TITLE
有个问题想请教大佬！

### ISSUE THREAD

**Issue by Yichengxuan** [pzx521521/SomeSSServerInChina#4]
如果在未知密码的情况下，能否跳过验证直接使用加速功能？

**Comment by pzx521521** [comment]
可以的, 他软件做的有问题, 正确的控制方式是在服务器生成 特定端口/特定密码 来控制流量
他仅仅在本地有一个时间验证
所以有几个思路:
1.修改网络有效时间
2.Hook修改本地时间(具体代码可以参考我的另外一个DllHookInject)
3.屏蔽验证时间
README.md 里面有写:
推荐直接od 搜"服务到期提醒" 有2个地方 把上面的je改为jmp

**Comment by Yichengxuan** [comment]
> 可以的，他软件做的有问题，正确的控制方式是在服务器生成特定端口/特定密码来控制流量
> 他仅仅在本地有一个时间验证
> 所以有几个思路：
> 1。修改网络有效时间
> 2.Hook修改本地时间（具体代码可以参考我的另外一个DllHookInject）
> 3。屏蔽验证时间
> README.md里面有写：
> 推荐直接od搜“服务到期提醒”有2个地方把上面的je改为jmp

好的，非常感谢大佬指点！
