### ISSUE TITLE
大佬我有个问题咨询

### ISSUE THREAD

**Issue by donggedaye** [pzx521521/SomeSSServerInChina#5]
大佬你好，就是我先打开加速器，然后od是吾爱网盘下载的，附加小白加速器这个进程，但打开后发现，地址码都是7767等等，不是大佬你们的00011那些，而且中文分词搜索后，也是乱码等，能麻烦大佬指导一下吗？

**Comment by donggedaye** [comment]
![1](https://user-images.githubusercontent.com/31370100/58606606-ca467600-82ce-11e9-8615-99e7aaa4fc61.png)
![2](https://user-images.githubusercontent.com/31370100/58606607-ca467600-82ce-11e9-9525-2aa7d2164801.png)

**Comment by Nimamadewen** [comment]
系统领空 清理下配置文件.......
